# Development Properties
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/lms_dev_db}
spring.data.mongodb.database=lms_dev_db

# Logging
logging.level.com.lms=DEBUG
logging.level.org.springframework.security=DEBUG

# JWT Secret (Dev only)
jwt.secret=judS2K4z5A+201mRU8I+CMNuqshK/JjuTvh27/Yq9E8=
jwt.expiration=3600000
jwt.refresh-expiration=86400000

# Mail (Dev)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=temporarymail2611@gmail.com
spring.mail.password=exws avpo txvs hwno
